#! /bin/bash
# From https://github.com/asayers/xmobar-tools
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this
# program. If not, see http://www.gnu.org/licenses/

# TODO: Use amixer rather than /proc to determine mute status

# $MUTE is the 'n' of "on" if the sound is muted, the 'f' of "off" if not
MUTE=`cat /proc/acpi/ibm/volume | tail -c 2`
if [ "$MUTE" == "n" ]; then
       COLOUR="red"
else
 	COLOUR="green"
fi

# Returns the current master volume; requires alsa-utils
VALUE=`amixer get Master | sed s/%.*$// | sed 's/^.*\[//' | tail -n 1`

# Format and print
echo "<fc=$COLOUR>$VALUE</fc>%"

